name: Build & Deploy JobTracker to Cloud Run

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: norse-carport-484915-f2
  REGION: us-central1
  REPO: jobtracker
  IMAGE: jobtracker-core
  IMAGE_TAG: ${{ github.sha }}
  SERVICE_NAME: jobtracker

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ---------------------------
      # Checkout
      # ---------------------------
      - name: Checkout source code
        uses: actions/checkout@v4

      # ---------------------------
      # Authenticate to GCP (OIDC)
      # ---------------------------
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/862280791858/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-ci@norse-carport-484915-f2.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      # ---------------------------
      # Docker auth (CRITICAL)
      # ---------------------------
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
          gcloud auth print-access-token | docker login \
            -u oauth2accesstoken \
            --password-stdin https://us-central1-docker.pkg.dev

      # ---------------------------
      # Build image
      # ---------------------------
      - name: Build Docker image
        run: |
          docker build \
            -t us-central1-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:$IMAGE_TAG .

      # ---------------------------
      # Push image
      # ---------------------------
      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:$IMAGE_TAG

      # ---------------------------
      # Deploy to Cloud Run
      # ---------------------------
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image us-central1-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:$IMAGE_TAG \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --port 8080
