name: Build and Push Docker Image to GCP Artifact

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: norse-carport-484915-f2
  REGION: us-central1
  REPO: jobtracker
  IMAGE: jobtracker-core

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
        service_account: "github-ci@${{ env.PROJECT_ID }}.iam.gserviceaccount.com"

    - name: Configure Docker
      run: |
        gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

    - name: Build and Push Image
      run: |
        docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:latest .
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:latest
