name: Build, Push & Deploy JobTracker to GKE

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: norse-carport-484915-f2
  REGION: us-central1
  REPO: jobtracker
  IMAGE: jobtracker-core
  IMAGE_TAG: ${{ github.sha }}
  CLUSTER_NAME: jobtracker-gke
  CLUSTER_LOCATION: us-central1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to GCP (OIDC)
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/862280791858/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: github-ci@norse-carport-484915-f2.iam.gserviceaccount.com

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
        docker build \
          -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:$IMAGE_TAG .

    - name: Push Docker image
      run: |
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:$IMAGE_TAG

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials \
          $CLUSTER_NAME \
          --region $CLUSTER_LOCATION \
          --project $PROJECT_ID

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/jobtracker-core \
          jobtracker-core=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:$IMAGE_TAG \
          -n jobtracker

    - name: Verify rollout
      run: |
        kubectl rollout status deployment/jobtracker-core -n jobtracker
