name: Build, Push & Deploy JobTracker to GKE

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: norse-carport-484915-f2
  REGION: us-central1
  REPO: jobtracker
  IMAGE: jobtracker-core
  IMAGE_TAG: ${{ github.sha }}
  CLUSTER_NAME: jobtracker-gke
  CLUSTER_LOCATION: us-central1
  NAMESPACE: jobtracker

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ---------------------------
      # Checkout
      # ---------------------------
      - name: Checkout source code
        uses: actions/checkout@v4

      # ---------------------------
      # Authenticate to GCP (OIDC)
      # ---------------------------
      - name: Authenticate to Google Cloud (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/862280791858/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-ci@norse-carport-484915-f2.iam.gserviceaccount.com

      # ---------------------------
      # Configure Docker
      # ---------------------------
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      # ---------------------------
      # Build Docker Image
      # ---------------------------
      - name: Build Docker image
        run: |
          docker build \
            -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:$IMAGE_TAG .

      # ---------------------------
      # Push Docker Image
      # ---------------------------
      - name: Push Docker image
        run: |
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:$IMAGE_TAG

      # ---------------------------
      # Get GKE Credentials (OFFICIAL)
      # ---------------------------
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.CLUSTER_LOCATION }}
          project_id: ${{ env.PROJECT_ID }}

      # ---------------------------
      # Deploy to GKE
      # ---------------------------
      - name: Deploy to GKE
        run: |
          kubectl set image deployment/jobtracker-core \
            jobtracker-core=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:$IMAGE_TAG \
            -n $NAMESPACE

      # ---------------------------
      # Verify Rollout
      # ---------------------------
      - name: Verify deployment rollout
        run: |
          kubectl rollout status deployment/jobtracker-core -n $NAMESPACE
